### ISSUE TITLE
Should master be compilable?

### ISSUE THREAD

**Issue by jdillon** [google/MOE#15]
```
> ant jar
Buildfile: /Users/jason/ws/reference/MOE/build.xml

clean:
   [delete] Deleting directory /Users/jason/ws/reference/MOE/build

compile:
    [mkdir] Created dir: /Users/jason/ws/reference/MOE/build/classes
    [javac] /Users/jason/ws/reference/MOE/build.xml:33: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 153 source files to /Users/jason/ws/reference/MOE/build/classes
    [javac] /Users/jason/ws/reference/MOE/java/com/google/devtools/moe/client/repositories/Revision.java:12: error: cannot find symbol
    [javac] import com.google.gson.annotations.JsonAdapter;
    [javac]                                   ^
    [javac]   symbol:   class JsonAdapter
    [javac]   location: package com.google.gson.annotations
    [javac] /Users/jason/ws/reference/MOE/java/com/google/devtools/moe/client/repositories/Revision.java:24: error: cannot find symbol
    [javac] @JsonAdapter(AutoValueGsonAdapter.class)
    [javac]  ^
    [javac]   symbol: class JsonAdapter
    [javac] /Users/jason/ws/reference/MOE/java/com/google/devtools/moe/client/database/SubmittedMigration.java:8: error: cannot find symbol
    [javac] import com.google.gson.annotations.JsonAdapter;
    [javac]                                   ^
    [javac]   symbol:   class JsonAdapter
    [javac]   location: package com.google.gson.annotations
    [javac] /Users/jason/ws/reference/MOE/java/com/google/devtools/moe/client/database/SubmittedMigration.java:18: error: cannot find symbol
    [javac] @JsonAdapter(AutoValueGsonAdapter.class)
    [javac]  ^
    [javac]   symbol: class JsonAdapter

BUILD FAILED
/Users/jason/ws/reference/MOE/build.xml:33: Compile failed; see the compiler error output for details.

Total time: 1 second
```

Doesn't appear to work for me :-(

```
 find build/classes/
build/classes/
build/classes//com
build/classes//com/google
build/classes//com/google/devtools
build/classes//com/google/devtools/moe
build/classes//com/google/devtools/moe/client
build/classes//com/google/devtools/moe/client/database
build/classes//com/google/devtools/moe/client/database/AutoValue_RepositoryEquivalence.java
build/classes//com/google/devtools/moe/client/database/AutoValue_SubmittedMigration.java
build/classes//com/google/devtools/moe/client/repositories
build/classes//com/google/devtools/moe/client/repositories/AutoValue_Repository.java
build/classes//com/google/devtools/moe/client/repositories/AutoValue_Revision.java
```

Ran into a problem a bit before when the ant build said it succeeded but the google auto-value processor actually aborted the build, generating a single .java file.  Today though, looks like its failing for other reasons, but unsure if its related or not.

**Comment by jdillon** [comment]
Post conversion to maven, this builds now, but doesn't produce a runnable jar

**Comment by cgruber** [comment]
It's all in progress.  I'll be adding maven jazz to build a binary
shortly.  Sorry for the delay.

**Comment by jdillon** [comment]
@cgruber okay good to get a reply back and know folks are on it.  We are really interested to start using this.  If you guys need any help with any of the maven bits, I'm more than willing to lend a hand, but doesn't seem to complex for what you are after.  But still.

**Comment by cgruber** [comment]
I've got it.  It's just been a matter of time, while I do other things
(like some re-design and features which will be coming out soon)

**Comment by cgruber** [comment]
Aaaand alot of time has gone by, and I apologize, but we're re-owrkign a lot of our internal open-source infrastructure and I got roped in. I will be attempting to fix all this and get #26 done this and next week.

**Comment by cgruber** [comment]
Part of what I need to do is move the external build bits into the internal repository so we can test it in eihter place, so changes that can't be built don't sneak in.

**Comment by jdillon** [comment]
mkay, offer to help still stands if you guys need help to get the mvn side of the config sorted

**Comment by jdillon** [comment]
@cgruber I see its compiling now, and the jar executes yay... but what is the state of the tool generally?

I have a very simple internal git project that needs to be exposed as a public git repo, with very minor changes (omit the entire private/** tree) and replace the top-level README.md.  Is MOE in its current state able to do that?  If so can you point me at some current docs or an example of how that works?

Thanks!

**Comment by cgruber** [comment]
Sorry - it's been a while, and I apologize.  I've made strides.  We decidedly use it a lot internally, so the state of it is good, but I have to sync out the docs and scrub them.  (And fix the README.md obviously).

Since this is compiling now, I"m going to close this issue, and open a few others.  As to how it works, ping me (cgruber@google.com) directly, and I can talk you through it.  I'll be honest, I've simply not used it outside of google, and our integration tests are not yet open-sourced, so there may be rough edges.

**Comment by H1414** [comment]
س![Uploading 94361897...]

**Comment by H1414** [comment]
سك![Uploading 94361927...]
