### ISSUE TITLE
Starter flow instructions are missing

### ISSUE THREAD

**Issue by yakovo** [google/MOE#34]
Hi,
we're trying to play with MOE, so we started with two simple GIT repos with identical content, and we would like to see how we can sync our commits from one repo to another. 
We could not find in the documentation the directives' sequence to follow in order to achieve our goal.
Is it possible to share the steps to take for this basic flow: two repos start with identical content, then the first repo is promoted with a commit, and finally, sync the commit to the second repo.

Thanks!

**Comment by yakovo** [comment]
Ok, we found that create_codebase -> change -> magic syncs a commit to a local clone. With that, we had to push manually...

**Comment by cgruber** [comment]
Yeah.  Sorry.  We have some internal documentation that I never exported.
I need to do that.
